### ISSUE TITLE
Multiple users to "own" the same dat.

### ISSUE THREAD

**Issue by martinheidegger** [joehand/hypercloud#115]
Hypercloud has upload limits & a "remove button" _(which are awesome)_ but this means that someone could publish dat and then at a later point remove it. If another person wants to make sure that a certain dat stays alive even if another person decides to remove it then she might want to "upload" the same dat under her account in order to make sure that it stays available (and for the url to be correct). The current [`'This archive is already being hosted by someone else'`](https://github.com/datprotocol/hypercloud/blob/master/lib/apis/archives.js#L77) is counter-productive in that case. Would it be okay to change this to "allowed"?

**Comment by martinheidegger** [comment]
Oh, I just saw that this is [`Temporary`](https://github.com/datprotocol/hypercloud/blob/master/lib/dbs/archives.js#L166) as of https://github.com/datprotocol/hypercloud/commit/aa350c4b7fe80870650f0a1a30262b3d90009dcd _(7 months ago)_. Why is that?

**Comment by pfrazee** [comment]
FWIW the blue link labs team forked hypercloud to https://github.com/beakerbrowser/hashbase and that's the one we actively maintain.

IIRC the only reason for that rule is to reduce complexity.

**Comment by martinheidegger** [comment]
Oh thanks, I actually came to this repo because of the link on the hashbase homepage :)

**Comment by pfrazee** [comment]
Whoops!

On Wed, Dec 13, 2017 at 10:00 AM, Martin Heidegger <notifications@github.com

**Comment by martinheidegger** [comment]
Closing this issue in favor of https://github.com/beakerbrowser/hashbase/issues/60
