### ISSUE TITLE
Move this repo out of datprotocol org?

### ISSUE THREAD

**Issue by bnewbold** [joehand/hypercloud#116]
Most other repos under the `datprotocol` github org are standards, documentation, or website related, not actual projects or implementations in code.

Would it make sense to move this repo (and maybe dat-dns, hypercloud-admin-cli, hypercloud-ui-vanilla) to the datproject or beakerbrowser orgs, or to individual user repos?

cc: @taravancil @pfrazee

**Comment by pfrazee** [comment]
This repo actually turned into https://github.com/beakerbrowser/hashbase so unless anybody objects, I'll just move this repo into my personal github for archival.

**Comment by pfrazee** [comment]
I'm going to move forward with the transfer so that it just gets done (tm) but Im happy to move it elsewhere if somebody has use for it.
