### ISSUE TITLE
Update the Register -> Add user flow

### ISSUE THREAD

**Issue by joehand** [joehand/hypercloud#3]
In the spec we had register and read user archive as a single flow. 

I think it makes sense to keep those as separate events. The register could be over HTTP eventually. But the read user archive will always need to happen on the user's machine (where the dat is). 

I made an [add user](https://github.com/joehand/hypercloud/blob/master/index.js#L28) endpoint we could use to read the archive and do all the other fun stuff.

**Comment by pfrazee** [comment]
I don't totally follow. Here's the register flow, can you pull it apart into your two proposed flows?

- User: creates new profile-dat
- User POSTS: account info, including profile-dat-url
- Server RESPONDS: proof file contents
- User: writes proof file to profile-dat
- User/Server: sync profile-dat
- User GETs: /{profile-dat-key}?view=status

**Comment by joehand** [comment]
Sorry, I guess we had the `/register` stuff under `/auth`, [signin flow](https://hackmd.io/s/HJHPnsBNl#v1auth). That should actually be register flow. So the proposal is to have a user do:

`/register`

* User POSTS: email & password
* Server: generates token
* Server RESPONDS: token & key
* User stores token/key and uses in auth headers

Then do

`/verify` (or `/create` maybe)

* User: creates new profile-dat
* User POSTS **WITH AUTH TOKEN IN HEADER**: account info, including profile-dat-url
* Server RESPONDS: proof file contents
* User: writes proof file to profile-dat
* User/Server: sync profile-dat
* User GETs **WITH AUTH TOKEN**: /{profile-dat-key}?view=status

The idea is that a user will get an auth token first and make subsequent HTTP requests with that token.

`/register` to get the auth token is consistent with what we've been doing on other township servers, so I'd like to keep that consistent.

**Comment by pfrazee** [comment]
Ok that flow would work fine. What I had in mind just merged those two flows together; when you POST the email & password, you would post the new profile-dat as well.

But that separation works. Maybe the second route is `/profile`, with a POST to update and a GET to read.

**Comment by pfrazee** [comment]
TODO: update the spec

**Comment by pfrazee** [comment]
@joehand actually this doesn't quite work. We need the initial POST to /register to trigger a confirmation email. The email needs to send a verification link, and then that verify needs to provide the session token.

**Comment by pfrazee** [comment]
New spec: https://github.com/joehand/hypercloud/wiki/Registration-Flow
