### ISSUE TITLE
Test suite doesnt exit on finish

### ISSUE THREAD

**Issue by pfrazee** [joehand/hypercloud#5]
I've tracked this down to archiver-server. It keeps some handle open.

**Comment by joehand** [comment]
`swarm.close(cb)` should be all we need.

**Comment by pfrazee** [comment]
Closing the swarm didnt solve it. Searching for other open handles...

**Comment by joehand** [comment]
I may have missed closing all the timeouts in archiver-server if its a timeout handle open.

**Comment by pfrazee** [comment]
I'll check into that

**Comment by pfrazee** [comment]
No it doesnt look like it's the archiver-server. The timeouts are getting closed, and if I dont initiate it, the issue persists

**Comment by pfrazee** [comment]
Ok, found the last hanger-on. Solved in the PR
