### ISSUE TITLE
Archive progress calculation issues

### ISSUE THREAD

**Issue by pfrazee** [joehand/hypercloud#50]
Two issues observed:

 1. Because hypercore will stall a .get() call until some replication occurs, an archive that isn't found can hang the request indefinitely. We need a version of .get() that returns immediately with an error if not found.
 2. The progress report can vacillate between 0 and 100 and back to 0, no idea why.

**Comment by joehand** [comment]
> Because hypercore will stall a .get() call until some replication occurs, an archive that isn't found can hang the request indefinitely. We need a version of .get() that returns immediately with an error if not found.

If the key hasn't been added to hypercore-archiver then it should [return immediately](https://github.com/mafintosh/hypercore-archiver/blob/master/index.js#L141) with an error. Is this situation where it's added but doesn't have any data yet? e.g. is it [the feed.get call](https://github.com/mafintosh/hypercore-archiver/blob/master/index.js#L147) that is hanging?

**Comment by pfrazee** [comment]
Probably feed.get, I havent double-checked. One of the hypercore calls (probably feed.get) will queue its CBs if data isn't there yet, so that when the download occurs it can provide with the data. We just need a way to toggle that behavior.
