### ISSUE TITLE
Can we expect connections initiated by hypercloud, to user devices, via the DHT, to succeed?

### ISSUE THREAD

**Issue by pfrazee** [joehand/hypercloud#57]
I'm currently debugging the connectivity between Beaker and Hypercloud, when Hypercloud is on a VPS.

**Condition** Hypercloud discovered my device via the DHT, but my device did not discover Hypercloud. Hypercloud attempted to connect to my device, but failed. This is, presumably, because my device is behind the NAT.

**Question** Since there's no hole-punching involved there, it's just impossible that the connection would succeed. For DHT discovery, the only option is that my device initiates the connection. Correct?

**Comment by pfrazee** [comment]
cc @mafintosh

**Comment by mafintosh** [comment]
Yes. You'd have to wait for the client to enter a new DHT lookup cycle (~5mins). Alternatively if you are also using dns discovery (using remote dns servers) it should just work right now as the VPS' address will be pushed to the client.

**Comment by pfrazee** [comment]
Ok cool. DNS discovery wasnt working, which is what I was investigating before bed.
