### ISSUE TITLE
Global Activity Stream

### ISSUE THREAD

**Issue by pfrazee** [joehand/hypercloud#66]
It'd be handy to see activity on the site, but I'm not yet sure what all we'll need, API-wise. I can imagine the following activity views:

 - Global activity view
 - Per-user activity view
 - List of users activity view (eg for an inbox)

For now, let's have a simple global activity stream, so that we can show what's happening in the service.

**Comment by joehand** [comment]
I know we talked about this but can't remember - are all archives published going to be public for now?

**Comment by pfrazee** [comment]
Yeah
